FROM trinera/cdk-client:3.0.14-beta

COPY web-client-nginx.conf /etc/nginx/conf.d/default.conf
COPY web-client-entrypoint.sh /gigatiff-entrypoint.sh

RUN sed -i 's/\r$//' /gigatiff-entrypoint.sh && chmod +x /gigatiff-entrypoint.sh

ENTRYPOINT ["/gigatiff-entrypoint.sh"]
