#configuration file for module 'import-mets-7.0.34-dev'
#Mon Apr 08 16:07:10 UTC 2024
convert.useImageServer=true
convert.imageServerTilesURLPrefix=http://host.docker.internal:18082/iiif/3
convert.imageServerImagesURLPrefix=http://host.docker.internal:18082/iiif/3
convert.imageServerSuffix.removeFilenameExtensions=false
convert.imageServerSuffix.tiles=
convert.imageServerSuffix.big=/full/max/0/default.jpg
convert.imageServerSuffix.thumb=/full/,128/0/default.jpg
convert.imageServerSuffix.preview=/full/,700/0/default.jpg
convert.imageServerDirectory=/mnt/imageserver/iip-data
convert.imageServerDirectorySubfolders=true

convert.useAudioServer=true
convert.audioServerURLPrefix=http://audioserver.inovatika.dev
convert.audioServerDirectory=/mnt/imageserver/audioserver
convert.audioServerDirectorySubfolders=true
